package org.tinitalk.media

import androidx.test.core.app.ApplicationProvider
import com.google.gson.JsonObject
import org.tinitalk.data.signal.SignalEvent
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.coroutines.Continuation
import kotlin.coroutines.EmptyCoroutineContext
import kotlin.coroutines.startCoroutine
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit

/** Characterizes the real SDP generated by the pinned WebRTC native library. */
class WebRtcCallSessionInstrumentedTest {
    @Test
    fun videoDisallowedOfferHasNoVideoMediaSection() {
        val context = ApplicationProvider.getApplicationContext<android.content.Context>()
        val session = WebRtcCallSession.create(context, videoAllowed = false)

        runBlockingLite {
            try {
                val offer = session.createOffer()

                assertEquals(0, videoMediaSectionCount(offer))
            } finally {
                session.close()
                session.close()
            }
        }
    }

    @Test
    fun videoAllowedOfferHasOneVideoMediaSectionWithoutOpeningCamera() {
        val context = ApplicationProvider.getApplicationContext<android.content.Context>()
        val session = WebRtcCallSession.create(context, videoAllowed = true)

        runBlockingLite {
            try {
                val offer = session.createOffer()

                assertEquals(1, videoMediaSectionCount(offer))
                assertTrue(videoMediaSection(offer).lineSequence().any { it == "a=sendrecv" })
                assertTrue(encodedOfferSize(offer) <= SignalEvent.MAX_EVENT_BYTES)
            } finally {
                session.close()
                session.close()
            }
        }
    }

    private fun videoMediaSectionCount(sdp: String): Int =
        Regex("(?m)^m=video\\s").findAll(sdp).count()

    private fun videoMediaSection(sdp: String): String =
        requireNotNull(Regex("(?ms)^m=video\\s.*?(?=^m=|\\z)").find(sdp)?.value)

    private fun encodedOfferSize(sdp: String): Int = SignalEvent(
        id = "018f7d51-3f90-7e63-b657-4a83a6a90210",
        callId = "018f7d51-40a1-7bb5-a2d0-7e47f9181766",
        type = "rtc.offer",
        sentAt = 1787666400000,
        payload = JsonObject().apply { addProperty("sdp", sdp) },
    ).encode().toByteArray(Charsets.UTF_8).size

    private fun runBlockingLite(block: suspend () -> Unit) {
        val done = CountDownLatch(1)
        var failure: Throwable? = null
        block.startCoroutine(
            object : Continuation<Unit> {
                override val context = EmptyCoroutineContext
                override fun resumeWith(result: Result<Unit>) {
                    failure = result.exceptionOrNull()
                    done.countDown()
                }
            },
        )
        check(done.await(10, TimeUnit.SECONDS)) { "Timed out waiting for media session" }
        failure?.let { throw it }
    }
}
